// Generated by scripts/generate-build-version.mjs. Do not edit by hand.
// The value is compiled into dist so packaged runtimes never read package.json.
export const GENERATED_SUPER_MCP_BUILD_VERSION = "2.7.6" as const;
